In [1]:
import sys
sys.path.append('../')
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '2'

import warnings
warnings.filterwarnings('ignore')
from data.pipe import BartNERPipe
from model.bart import BartSeq2SeqModel
import fitlog
import random
import numpy as np

import torch
from fastNLP import Trainer
from model.metrics import Seq2SeqSpanMetric
from model.losses import Seq2SeqLoss
from torch import optim
from fastNLP import BucketSampler, GradientClipCallback, cache_results

from model.callbacks import WarmupCallback
from fastNLP.core.sampler import SortedSampler
from model.generater import SequenceGeneratorModel
from fastNLP.core.sampler import  ConstTokenNumSampler
from model.callbacks import FitlogCallback

fitlog.debug()
fitlog.set_log_dir('logs')

import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--dataset_name', default='re_ace05', type=str)

def set_seed(seed=1996):
    print("[SET SEED]: ",seed)
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True

args= parser.parse_args([])
dataset_name = args.dataset_name
args.length_penalty = 1
args.save_model = 1

# word: 生成word的start; bpe: 生成所有的bpe; span: 每一段按照start end生成; span_bpe: 每一段都是start的所有bpe，end的所有bpe
args.target_type = 'word'
args.bart_name = '/disk1/wxl/Desktop/DeepKE/example/ner/huggingface/bart-large'
args.schedule = 'linear'
args.decoder_type = 'avg_feature'
args.n_epochs = 30
args.num_beams = 1
args.batch_size = 16
args.use_encoder_mlp = 1
args.lr = 1e-5
args.warmup_ratio = 0.01
eval_start_epoch = 1

# the following hyper-parameters are for target_type=word
if dataset_name == 'conll2003':  # three runs get 93.18/93.18/93.36 F1
    max_len, max_len_a = 10, 0.6
elif dataset_name == 'en-ontonotes':  # three runs get 90.46/90.4/90/52 F1
    max_len, max_len_a = 10, 0.8
elif dataset_name == 'CADEC':
    max_len, max_len_a = 10, 1.6
    args.num_beams = 4
    args.lr = 2e-5
    args.n_epochs = 30
    eval_start_epoch=10
elif dataset_name == 'Share_2013':
    max_len, max_len_a = 10, 0.6
    args.use_encoder_mlp = 0
    args.num_beams = 4
    args.lr = 2e-5
    eval_start_epoch = 5
elif dataset_name == 'Share_2014':
    max_len, max_len_a = 10, 0.6
    args.num_beams = 4
    eval_start_epoch = 5
    args.n_epochs = 30
elif dataset_name == 'genia':  # three runs: 79.29/79.13/78.75
    max_len, max_len_a = 10, 0.5
    args.target_type = 'span'
    args.lr = 2e-5
    args.warmup_ratio = 0.01
elif dataset_name == 'en_ace04':  # four runs: 86.84/86.33/87/87.17
    max_len, max_len_a = 50, 1.1
    args.n_epochs = 55
    args.batch_size = 48
    args.lr = 4e-5
    seed = 4373
elif dataset_name == 're_ace05':
    max_len, max_len_a = 10, 1.6
    args.num_beams = 4
    args.lr = 2e-5
    args.batch_size = 80
    args.n_epochs = 100
    seed = 3257
    eval_start_epoch=1
elif dataset_name == 'en_ace05':  # three runs: 85.39/84.54/84.75
    max_len, max_len_a = 50, 0.7
    args.lr = 3e-5
    args.batch_size = 12
    args.num_beams = 4
    args.warmup_ratio = 0.1

set_seed(seed)
# with open("/disk1/wxl/Desktop/DeepKE/example/baseline/BARTNER/loss_log/D.json","r") as f:
#     b=f.readlines()
# with open("/disk1/wxl/Desktop/DeepKE/example/baseline/BARTNER/loss_log/E.json","r") as f:
#     c=f.readlines()
# for x,y in zip(b,c):
#     assert x==y,print(x,y)
# exit()

save_model = args.save_model
del args.save_model
lr = args.lr
n_epochs = args.n_epochs
batch_size = args.batch_size
num_beams = args.num_beams

length_penalty = args.length_penalty
if isinstance(args.decoder_type, str) and args.decoder_type.lower() == 'none':
    args.decoder_type = None
decoder_type = args.decoder_type
target_type = args.target_type
bart_name = args.bart_name
schedule = args.schedule
use_encoder_mlp = args.use_encoder_mlp

fitlog.add_hyper(args)

#######hyper
#######hyper

demo = False
if demo:
    cache_fn = f"caches/data_{bart_name}_{dataset_name}_{target_type}_demo.pt"
else:
    cache_fn = f"caches/data_{bart_name}_{dataset_name}_{target_type}.pt"

@cache_results(cache_fn, _refresh=False)
def get_data():
    pipe = BartNERPipe(tokenizer=bart_name, dataset_name=dataset_name, target_type=target_type)
    if dataset_name == 'conll2003':
        paths = {'test': "./data/conll2003/test.txt",
                 'train': "./data/conll2003/train.txt",
                 'dev': "./data/conll2003/dev.txt"}
        data_bundle = pipe.process_from_file(paths, demo=demo)
    elif dataset_name == 'en-ontonotes':
        paths = './data/en-ontonotes/english'
        data_bundle = pipe.process_from_file(paths)
    else:
        data_bundle = pipe.process_from_file(f'./data/{dataset_name}', demo=demo)
    return pipe, data_bundle, pipe.tokenizer, pipe.mapping2id
print(f'max_len_a:{max_len_a}, max_len:{max_len}')

pybuilddir.txt
pybuilddir.txt
/usr/share/zoneinfo/UTC
/usr/lib/ssl/certs/ca-certificates.crt
[SET SEED]:  3257
max_len_a:1.6, max_len:10


In [2]:
pipe, data_bundle, tokenizer, mapping2id = get_data()
ds = data_bundle.get_dataset("test")
len(ds)

Read cache from caches/data_/disk1/wxl/Desktop/DeepKE/example/ner/huggingface/bart-large_re_ace05_word.pt.


2050

In [15]:
from fastNLP import DataSet,DataSetIter
from fastNLP import SequentialSampler
sampler = SequentialSampler()
batch = DataSetIter(batch_size=1, dataset=ds, sampler=sampler)
batch2 = DataSetIter(batch_size=2, dataset=ds, sampler=sampler)
# model2.eval()

In [16]:
from model.utils import get_span_from_pred
label_ids = list(mapping2id.values())
metric = Seq2SeqSpanMetric(1, num_labels=len(label_ids), target_type=target_type)
model2 = torch.load("/disk1/wxl/Desktop/DeepKE/example/baseline/BARTNER/save_models/re_ace05_3257_1734353331.4825141/best_SequenceGeneratorModel_f_2024-12-16-20-48-57-482293").to('cuda')
model2.eval()
max_type_id = len(pipe.mapping2targetid) + 2
pred_num = 0
all_ent_num = 0
false_num = 0
true_num = 0
false_pred_num = 0
false_list = []
true_list = [] 
false_pred_list = []
for id,i in enumerate(batch):
    #print(id)
    src_tokens=i[0]["src_tokens"]
    src_seq_len=i[0]["src_seq_len"]
    first=i[0]["first"]
    tgt_tokens = i[1]["tgt_tokens"].to('cuda')
    pred = model2.predict(src_tokens.to('cuda'), src_seq_len.to('cuda'), first.to('cuda'))['pred']
    pred_spans = [get_span_from_pred(pred[id], max_type_id) for id in range(pred.shape[0])]
    pred_spans = [set([str(y) for y in pred_spans[x]]) for x in range(pred.shape[0])]

    target_spans = [set([str(list(span)) for span in i[1]["target_span"][id]]) for id in range(pred.shape[0])]
    
    false_spans = [target_spans[id] - pred_spans[id] for id in range(pred.shape[0])] # 没预测出来的span
    # print(false_spans)
    true_spans = [target_spans[id] & pred_spans[id] for id in range(pred.shape[0])] # 预测出来的span
    # x = [list(ss) for ss in pred_spans]
    # y = [list(ss) for ss in target_spans]
    # for xx in x:
    #     xx.sort()
    # for yy in y:
    #     yy.sort()
    # print("pred_spans: ",x, "\ntarget_spans",y,"\n")
    print(pred)
    print("pred_spans: ",pred_spans, "\ntarget_spans",target_spans,"\n")
    if id > 4:
        break
    false_pred_spans = [pred_spans[id] - target_spans[id] for id in range(pred.shape[0])]
    # x = [list(ss) for ss in false_spans]
    # y = [list(ss) for ss in false_pred_spans]
    # for xx in x:
    #     xx.sort()
    # for yy in y:
    #     yy.sort()
    # print("false_spans: ",x, "\nfalse_pred_spans",y,"\n")
    # pred_num += sum([len(x[i]) for i in range(pred.shape[0])])
    all_ent_num += sum(len(i[1]["target_span"][id]) for id in range(pred.shape[0]))
    false_num += sum([len(fs) for fs in false_spans])
    true_num += sum([len(ts) for ts in true_spans])
    false_pred_num += sum(len(fps) for fps in false_pred_spans)
    false_list += false_spans
    true_list += true_spans
    false_pred_list += false_pred_spans
    res = metric.evaluate(i[1]["target_span"], pred, tgt_tokens)
    # print("pred: ",pred, "\ntarget: ",tgt_tokens,"\n")
print(metric.get_metric())
print(true_num, " ", false_num, " ", false_pred_num)
print(all_ent_num)

# print("=================")

label_ids = list(mapping2id.values())
metric = Seq2SeqSpanMetric(1, num_labels=len(label_ids), target_type=target_type)
model2.eval()
max_type_id = len(pipe.mapping2targetid) + 2
pred_num = 0
all_ent_num = 0
false_num = 0
true_num = 0
false_pred_num = 0
false_list = []
true_list = [] 
false_pred_list = []
for id,i in enumerate(batch2):
    src_tokens=i[0]["src_tokens"]
    src_seq_len=i[0]["src_seq_len"]
    first=i[0]["first"]
    tgt_tokens = i[1]["tgt_tokens"].to('cuda')
    pred = model2.predict(src_tokens.to('cuda'), src_seq_len.to('cuda'), first.to('cuda'))['pred']
    print(pred)
    pred_spans = [get_span_from_pred(pred[id], max_type_id) for id in range(pred.shape[0])]
    pred_spans = [set([str(y) for y in pred_spans[x]]) for x in range(pred.shape[0])]

    target_spans = [set([str(list(span)) for span in i[1]["target_span"][id]]) for id in range(pred.shape[0])]
    
    false_spans = [target_spans[id] - pred_spans[id] for id in range(pred.shape[0])] # 没预测出来的span
    #print(false_spans)
    true_spans = [target_spans[id] & pred_spans[id] for id in range(pred.shape[0])] # 没预测出来的span
    x = [list(ss) for ss in pred_spans]
    y = [list(ss) for ss in target_spans]
    for xx in x:
        xx.sort()
    for yy in y:
        yy.sort()
    print("pred_spans: ",pred_spans, "\ntarget_spans",target_spans,"\n")
    if id > 1:
        break
    false_pred_spans = [pred_spans[id] - target_spans[id] for id in range(pred.shape[0])]
    pred_num += sum([len(x[i]) for i in range(pred.shape[0])])
    all_ent_num += sum(len(i[1]["target_span"][id]) for id in range(pred.shape[0]))
    false_num += sum([len(fs) for fs in false_spans])
    true_num += sum([len(ts) for ts in true_spans])
    false_pred_num += sum(len(fps) for fps in false_pred_spans)
    false_list += false_spans
    true_list += true_spans
    false_pred_list += false_pred_spans
    res = metric.evaluate(i[1]["target_span"], pred, tgt_tokens)
    #print("pred: ",pred, "\ntarget: ",tgt_tokens,"\n")
print(metric.get_metric())
print(true_num, " ", false_num, " ", false_pred_num)
print(all_ent_num)

tensor([[0, 1, 1]], device='cuda:0')
pred_spans:  [set()] 
target_spans [set()] 

tensor([[0, 1, 1]], device='cuda:0')
pred_spans:  [set()] 
target_spans [set()] 

tensor([[0, 1, 1]], device='cuda:0')
pred_spans:  [set()] 
target_spans [set()] 

tensor([[0, 1, 1]], device='cuda:0')
pred_spans:  [set()] 
target_spans [set()] 

tensor([[0, 1, 1]], device='cuda:0')
pred_spans:  [set()] 
target_spans [set()] 

tensor([[0, 1, 1]], device='cuda:0')
pred_spans:  [set()] 
target_spans [set()] 

正确预测个数： 0  错误预测个数： 0  未被预测的正确实体个数： 0
{'f': 0.0, 'rec': 0.0, 'pre': 0.0, 'em': 1.0}
0   0   0
0
tensor([[0, 1, 1],
        [0, 1, 1]], device='cuda:0')
pred_spans:  [set(), set()] 
target_spans [set(), set()] 

tensor([[0, 1, 1],
        [0, 1, 1]], device='cuda:0')
pred_spans:  [set(), set()] 
target_spans [set(), set()] 

tensor([[0, 1, 1],
        [0, 1, 1]], device='cuda:0')
pred_spans:  [set(), set()] 
target_spans [set(), set()] 

正确预测个数： 0  错误预测个数： 0  未被预测的正确实体个数： 0
{'f': 0.0, 'rec': 0.0, 'pre': 0

In [5]:
model2 = torch.load("/disk1/wxl/Desktop/DeepKE/example/baseline/BARTNER/save_models/en_ace04_569/best_SequenceGeneratorModel_f_2024-11-26-10-24-31-836238").to('cuda')
type(model2.seq2seq_model.decoder.decoder.layers[0].encoder_attn)
# x = model2.seq2seq_model.decoder.decoder.embed_tokens.weight[2:9]
# x = x.unsqueeze(0).expand(48, -1, -1)
# x.shape
# print(x[0],x[1])


FileNotFoundError: [Errno 2] No such file or directory: '/disk1/wxl/Desktop/DeepKE/example/baseline/BARTNER/save_models/en_ace04_569/best_SequenceGeneratorModel_f_2024-11-26-10-24-31-836238'